/* Used By Jenkins Job sfr-build-linux-package-modular */

/* Constant Declarations */

def NODE_LABEL = 'build&&linux&&x64&&dockerBuild&&dynamicAzure' // Default node
def PRODUCT = 'temurin'
def JVM = 'hotspot'
def baseURL = "https://github.com/adoptium/"
def binaryRepo = "${params.VERSION.replace('jdk', 'temurin')}-binaries/releases/tag/${params.TAG}"
def binaryDLRepo = "${params.VERSION.replace('jdk', 'temurin')}-binaries/releases/download/${params.TAG}"
def fullURL = "${baseURL}/${binaryRepo}"
def dlURL = "${baseURL}/${binaryDLRepo}"
def PKGBUILDLABEL=""

/* Supported Distro Arrays */
// Remember If Adding An Deb Distro to update the cacerts package //
def deb_distros = [
    "trixie", // Debian/13
    "bookworm", // Debian/12
    "bullseye", // Debian/11
    "buster",   // Debian/10
    "oracular", // Ubuntu/24.10 (STS)
    "noble",    // Ubuntu/24.04 (LTS)
    "jammy",    // Ubuntu/22.04 (LTS)
    "focal",    // Ubuntu/20.04 (LTS)
    "bionic"   // Ubuntu/18.04 (LTS)
    ]

def distro_list = ''
deb_distros.each { deb_version ->
        // Creates list like deb.distribution=stretch;deb.distribution=buster;
        distro_list += "deb.distribution=${deb_version};"
   }

def rhel_distros = [
    'rpm/centos/7',
    'rpm/rocky/8',
    'rpm/rhel/7',
    'rpm/rhel/8',
    'rpm/rhel/9',
    'rpm/fedora/35',
    'rpm/fedora/36',
    'rpm/fedora/37',
    'rpm/fedora/38',
    'rpm/fedora/39',
    'rpm/fedora/40',
    'rpm/fedora/41',
    'rpm/fedora/42',
    'rpm/fedora/rawhide',
    'rpm/oraclelinux/7',
    'rpm/oraclelinux/8',
    'rpm/amazonlinux/2'
    ]

def suse_distros = [
    'rpm/opensuse/15.3',
    'rpm/opensuse/15.4',
    'rpm/opensuse/15.5',
    'rpm/sles/12',
    'rpm/sles/15'
    ]

/* End Of Distro Definitions*/

// Global Variables
def DLfilenames = []
def JDKArray = []
def ModifiedJDKArray = []
def DISTS_TO_BUILD = []
def distro = ""
def arch = ""
def ReleaseVersion = ""
def Release = ""
def Version = ""
def Build = ""
def packagearch = ""
def packagearchDeb = ""
def packagearchRhel = ""
def PackageReleaseVersion = "0"
def upstreamversion = ""
def upstreamversionARM32 = ""
/* Have Some Default Node Labels */
def PKGBUILDLABELAPK = 'build&&linux&&x64&&dockerBuild&&dynamicAzure'
def PKGBUILDLABELDEB = 'build&&linux&&x64&&dockerBuild&&dynamicAzure'
def PKGBUILDLABELRHEL = 'build&&linux&&x64&&dockerBuild&&dynamicAzure'

// Function Definitions Begin

// Helper function to download and validate files
def validateAndDownloadArtifact(url, file) {
    echo "Downloading: ${url}"
    def result = sh(script: "curl -sSL -O ${url}", returnStatus: true)
    if (result != 0) {
        error("Failed to download ${file}. File not found or an error occurred.")
    }
    echo "Downloaded: ${file}"
}

// Helper function to validate checksum
def validateChecksum(file, checksumFile) {
    def expectedChecksum = sh(script: "awk '{print \$1}' ${checksumFile}", returnStdout: true).trim()
    def calculatedChecksum = sh(script: "sha256sum ${file} | awk '{print \$1}'", returnStdout: true).trim()
    if (expectedChecksum != calculatedChecksum) {
        error("Checksum mismatch for ${file}. Expected: ${expectedChecksum}, but found: ${calculatedChecksum}.")
    }
    echo "Checksum validation successful for ${file}."
    return calculatedChecksum
}

// Helper function to extract upstream version from tar file
def extractUpstreamVersionFromTar(file) {
    def version = sh(script: "tar xvfz \"${file}\" | head -n 1 | cut -d/ -f1", returnStdout: true).trim()
    sh "rm -rf \"${version}\""
    echo "Extracted upstream version: ${version}"
    return version
}

// Helper function to cleanup files
def cleanupFiles(files) {
    files.each { file ->
        sh "rm -rf ${file}"
    }
}

// Helper function to Set Node Labels
def getPackageBuildLabel(String arch, String distro) {
    switch (distro) {
        case 'APK':
            return (arch == 'x64') ? 'build&&linux&&x64&&dockerBuild&&dynamicAzure' :
                   (arch == 'aarch64') ? 'docker&&linux&&aarch64&&alpineInstaller' :
                   'build&&linux&&x64&&dockerBuild&&dynamicAzure'

        case 'DEB':
            return (arch == 'x64') ? 'build&&linux&&x64&&dockerBuild&&dynamicAzure' :
                   (arch == 'arm') ? 'docker&&linux&&aarch64' :
                   (arch == 'aarch64') ? 'docker&&linux&&aarch64' :
                   (arch == 'ppc64le') ? 'build&&docker&&ppc64le' :
                   (arch == 's390x') ? 'docker&&s390x&&dockerBuild' :
                   (arch == 'riscv64') ? 'dockerBuild&&linux&&riscv64&&dockerInstaller' :
                   
                   'build&&linux&&x64&&dockerBuild&&dynamicAzure'

        case 'RHEL':
            return 'build&&linux&&x64&&dockerBuild&&dynamicAzure'

        default:
            error("Unsupported distro: ${distro}")
    }
}

// Helper function to check and upload files
def CheckAndUpload(String Target, String Distro, String BuildArch, String Version, String DistroList, String Value, String PackageDir, String Key, String FileName) {
  echo "Entering Check & Upload"
  // Received From Alpine CheckAndUpload(Target, UpDistro, buildArch, '', '', '', '', '' , FileName)
  echo "Debug 1001"
  echo "Target = ${Target}"
  echo "Distro = ${Distro}"
  echo "Arch = ${BuildArch}"
  echo "DList = ${DistroList}"
  echo "Value = ${Value}"
  echo "PackageDir = ${PackageDir}"
  echo "Key = ${Key}"
  echo "Filename = ${FileName}"  



  // Set Env Vars For Debs & Rpms

//    env.BUILDARCH = BuildArch
//   env.VERSION = Version
//   env.DISTROLIST = DistroList
//   env.VALUE = Value
//   env.PACKAGEDIR = PackageDir
//   env.KEY = Key
//   env.FILENAME = FileName
//   try {
//     def ResponseCode = sh(script: "curl -o /dev/null --silent --head --write-out '%{http_code}' ${Target}", returnStdout: true).trim()
//     echo "ResponseCode = ${ResponseCode}"
//     if ( ResponseCode == '200') {
//       echo "Target Exists - Skipping"
//     } else {
//       echo "Target Doesnt Exist - Upload Files"
//       switch(Distro) {
//            case "Debian":
//                // Not RISC Use JF CLI
//                if (BuildArch != "riscv64") {
//                  jf 'rt u **/build/ospackage/temurin-*${BUILDARCH}.deb deb/pool/main/t/temurin-${VERSION}/ --target-props=${DISTROLIST}deb.component=main;deb.architecture=${BUILDARCH} --flat=true'
//                }
//                if (BuildArch == "riscv64") {
//                handleRISCVUpload("Debian", "${BUILDARCH}", "${VERSION}", "${DISTROLIST}", "", "", "")
//              }
//                break
//            case "Alpine":
//                jf 'rt u **/build/ospackage/${FILENAME} apk/alpine/main/${BUILDARCH}/ --flat=true'
//                break
//            case "RPMS":
//               if (BuildArch != "riscv64") {
//                 jf 'rt u **/build/ospackage/*.${VALUE}.rpm ${PACKAGEDIR}/${KEY}/Packages/ --flat=true'
//               }
//               if (BuildArch == "riscv64") {
//                 handleRISCVUpload("RPMS","" ,"", "", "${VALUE}", "${PACKAGEDIR}", "${KEY}" )
//               }
//               break
//            default:
//               echo "Default Case"
//               if (BuildArch != "riscv64") {
//                 jf 'rt u **/build/ospackage/*.${VALUE}.rpm ${PACKAGEDIR}/${KEY}/Packages/ --flat=true'
//               }
//               if (BuildArch == "riscv64") {
//                 handleRISCVUpload("RPMS","" ,"", "", "${VALUE}", "${PACKAGEDIR}", "${KEY}" )
//               }
//               break
//        }
//     }
//   } catch (Exception e) {
//     error "Error While Checking URL ${Target}: ${e.message}"
//   }
}

// Function Definitions End


/* Pipeline Declaration */
pipeline {
    agent none  // No Default Agent
    options {
        timeout(time: 2, unit: 'HOURS')
    }

      parameters {
          string(name: 'TAG', defaultValue: 'jdk-23+37', description: 'Release Tag')
          string(name: 'VERSION', defaultValue: 'jdk23', description: 'Release Version')
          string(name: 'ARTIFACTS_TO_COPY', defaultValue: '**/alpine-linux/aarch64/temurin/*.tar.gz,**/alpine-linux/aarch64/temurin/*.zip,**/alpine-linux/aarch64/temurin/*.sha256.txt,**/alpine-linux/aarch64/temurin/*.msi,**/alpine-linux/aarch64/temurin/*.pkg,**/alpine-linux/aarch64/temurin/*.json,**/alpine-linux/aarch64/temurin/*.sig', description: 'Artifacts String')
          booleanParam(name: 'RELEASE', defaultValue: false, description: 'Release Flag' )
          booleanParam(name: 'DRY_RUN', defaultValue: false, description: 'Release Dry Run')
          booleanParam(name: 'ENABLEGPGSIGNING', defaultValue: true, description: 'Require GPG Signing')
          booleanParam(name: 'ENABLEDEBUG', defaultValue: false, description: 'Tick to enable --stacktrace for gradle build')
          booleanParam(name: 'REPACKAGE', defaultValue: false, description: 'Tick if this is a republish of an existing package, ie xx.xxx.2 , rather than the base release of a package (1)')
          string(name: 'PACKAGE_INCREMENT', defaultValue: '1', description: 'This is the incremental number used for re-releases of package versions - Should be set appropriately if RePackage is True')
      }
// Stage Definition - Start
      stages {
// Print Parameters Stage - Start
          stage('Print Parameters') {
            agent { label NODE_LABEL }
              steps {
                  script {
                      echo "Tag : ${params.TAG}"
                      echo "Version : ${params.VERSION}"
                      echo "Artifacts : ${params.ARTIFACTS_TO_COPY}"
                      echo "Release : ${params.RELEASE}"
                      echo "Dry Run : ${params.DRY_RUN}"
                  }
              }
          }
// Print Parameters Stage - End
// Process Parameters Stage - Start
          stage('Process Parameters') {
            agent { label NODE_LABEL }
            // when {
            //     expression { return params.Release }
            // }
            steps {
                script{

                    // Figure Out Which Dist This Run Is For

                    if (params.ARTIFACTS_TO_COPY.contains('alpine-linux')) {
                        distro  = "alpine-linux"
                    } else if (params.ARTIFACTS_TO_COPY.contains('linux')) {
                        distro = "linux"
                    } else {
                        error("The Artifacts Are For Neither Linux OR Alpine")
                    }

                    // Figure Out Which Arch This Run Is For
                    if (params.ARTIFACTS_TO_COPY.contains('aarch64')) {
                        arch  = "aarch64"
                    } else if (params.ARTIFACTS_TO_COPY.contains('x64')) {
                        arch  = "x64"
                    } else if (params.ARTIFACTS_TO_COPY.contains('s390x')) {
                        arch  = "s390x"
                    } else if (params.ARTIFACTS_TO_COPY.contains('arm')) {
                        arch  = "arm"
                    } else if (params.ARTIFACTS_TO_COPY.contains('ppc64le')) {
                        arch  = "ppc64le"
                    } else if (params.ARTIFACTS_TO_COPY.contains('riscv64')) {
                        arch  = "riscv64"
                    } else {
                        error("The Artifacts Are For An Unsupported Architecture")
                    }

                    echo "DEBUG 00 - arch = ${arch}"

                    // Derive Node To Build Packages On

                    PKGBUILDLABELAPK = getPackageBuildLabel(arch, 'APK')
                    PKGBUILDLABELDEB = getPackageBuildLabel(arch, 'DEB')
                    PKGBUILDLABELRHEL = getPackageBuildLabel(arch, 'RHEL')

                    // Map Architectures From Source To Dist Suitable Values

                    packagearchDeb = (arch == 'x64') ? 'amd64' :
                                     (arch == 'arm') ? 'armhf' :
                                     (arch == 'aarch64') ? 'arm64' :
                                     (arch == 'ppc64le') ? 'ppc64el' :
                                     (arch == 's390x') ? 's390x' :
                                     (arch == 'riscv64') ? 'riscv64' :
                                     'unknown'

                    packagearchRhel = (arch == 'x64') ? 'x86_64' :
                                      (arch == 'arm') ? 'armv7hl' :
                                      (arch == 'aarch64') ? 'aarch64' :
                                      (arch == 'ppc64le') ? 'ppc64le' :
                                      (arch == 's390x') ? 's390x' :
                                      (arch == 'riscv64') ? 'riscv64' :
                                      'unknown'


                    // Version Number Parsing

                    def vername = ''
                    def verversion = ''
                    def verbuild = ''

                    // Add Special Handling For JDK8 Version Number
                    // jdk8u432-b06

                    if (params.TAG?.startsWith("jdk8")) {
                        echo "JDK 8"
                        def split = (params.TAG =~ /(jdk)(\d+u\d+)-(b\d+)/)
                        if (split.find()) {
                            // println("Full Match: ${split[0][0]}")
                            vername = split[0][1]          // "jdk"
                            verversion = split[0][2]       // "8u432"
                            verbuild = split[0][3]         // "06"
                            } else {
                                 error("The version string format does not match the expected pattern.")
                        }
                    } else {
                        echo "Not JDK8"
                    // Parse The Version Tag, Into Usable Components
                    
                    def split = (params.TAG =~ /(jdk)-(\d[\d.]*)([+_]\d+)?/)

                    if (split.find()) {
                        vername = split.group(1)
                        verversion = split.group(2)
                        verbuild = split.group(3)?.replaceAll("[+_]", "")
                    } else {
                        error("The version string format does not match the expected pattern.")
                    }

                    }

                    // Construct the Filename
                    def filennameFinal =""
                    def filenamePrefix = "Open"
                    def filenameSuffix = "tar.gz"
                    def filenameVersion = params.VERSION.toUpperCase() + "U"
                    def packageTypes = ['jdk', 'jre']

                    packageTypes.each { packageType ->
                      if (params.TAG?.startsWith("jdk8")) {
                        filenameFinal = "${filenamePrefix}${filenameVersion}-${packageType}_${arch}_${distro}_${JVM}_${verversion}${verbuild ?: 'N/A'}"
                        ReleaseVersion = "${verversion}${verbuild ?: 'N/A'}"
                      } else {
                        filenameFinal = "${filenamePrefix}${filenameVersion}-${packageType}_${arch}_${distro}_${JVM}_${verversion}_${verbuild ?: 'N/A'}"
                        ReleaseVersion = "${verversion}_${verbuild ?: 'N/A'}"
                      }
                      
                      def JDKFinal = "${filenameFinal}.${filenameSuffix}"
                      def SHAFinal = "${JDKFinal}.sha256.txt"
                      
                      echo "JDK File Name : ${JDKFinal}"
                      echo "SHA File Name : ${SHAFinal}"
                      DLfilenames << JDKFinal
                      DLfilenames << SHAFinal

                      JDKArray << [ "${packageType}" , "${JDKFinal}", "${SHAFinal}" , "${distro}" , "${arch}" , "${ReleaseVersion}" ]
                    }

                    // Set Package Release Version If Repackage
                    if (params.REPACKAGE) {
                        PackageReleaseVersion = params.PACKAGE_INCREMENT
                      }
                }
            }
          }
// Process Parameters Stage - End
// Validate Artifacts Stage - Start
stage('Validate Artifacts') {
    agent { label NODE_LABEL }
    // when {
    //     expression { return params.RELEASE }
    // }
    steps {
        script {
            echo "Validating Artifacts"
            echo "Tuples:"
            echo "${JDKArray}"

            JDKArray.each { ArrayElement ->
                def (PTYPE, PFILE, PSIGN, PDIST, PARCH, PVERS) = ArrayElement
                def Binurl = "${dlURL}/${PFILE}"
                def SHAurl = "${dlURL}/${PSIGN}"

                // Download binary and checksum
                validateAndDownloadArtifact(Binurl, PFILE)
                validateAndDownloadArtifact(SHAurl, PSIGN)

                // Validate checksum
                def calculatedChecksum = validateChecksum(PFILE, PSIGN)

                if (PARCH == "arm") {
                    upstreamversionARM32 = extractUpstreamVersionFromTar(PFILE)
                }

                // Cleanup temporary files
                cleanupFiles([PFILE, PSIGN])

                // Update array with the validated information
                ModifiedJDKArray << [PTYPE, PFILE, PSIGN, PDIST, PARCH, PVERS, calculatedChecksum, Binurl]
            }

            JDKArray = ModifiedJDKArray
        }
    }
}
// Generate Spec File Stage - Start
          stage('Generate Spec File') {
            agent { label NODE_LABEL }
            // when {
            //     expression { return params.RELEASE }
            // }
              steps {
                  script {
                      echo "Validating Required Parameters For Generate Spec File Program"
                      echo "Debug 02"
                      JDKArray.each { ArrayElement ->
                      echo "${ArrayElement}"
                      // Assign Tuple Values To Vars
                      def PTYPE = ArrayElement[0]
                      def PFILE = ArrayElement[1]
                      def PSIGN = ArrayElement[2]
                      def PDIST = ArrayElement[3]
                      def PARCH = ArrayElement[4]
                      def PVERS = ArrayElement[5]
                      def PCSUM = ArrayElement[6]
                      def PKURL = ArrayElement[7]
                      

                      // Generate Date For Use In Various Places
                      def getDate = new Date(currentBuild.startTimeInMillis)
                      // Format The Date
                      def currentDate = getDate.format("EEE, dd MMM yyyy HH:mm:ss Z", TimeZone.getTimeZone('UTC'))
                      def currentDateRHEL = getDate.format("EEE MMM d yyyy", TimeZone.getTimeZone('UTC'))
                      echo "Current Date: ${currentDate}"
                      echo "Current Date RHEL: ${currentDateRHEL}"

                      // Setup List Of Packages To Build
                      if (PDIST == 'alpine-linux') {
                         DISTS_TO_BUILD = ['alpine']
                        } else if (PDIST == 'linux') {
                            DISTS_TO_BUILD = ['rhel', 'suse', 'debian']
                            } else {
                                error("Unsupported dist: ${PDIST}")
                                }
                      DISTS_TO_BUILD.each { DistArrayElement ->
                      
                      echo "Debug 03"
                      if (params.TAG?.startsWith("jdk8")) {
                        echo "Debug 04"
                        echo "PVERS : ${PVERS}"

                        def versionPattern = /(\d+)(u\d+)(b\d+)/
                        def versparser = (PVERS =~ versionPattern)
                        println("Full Match: ${versparser[0][0]}")
                        if (versparser.matches()) {
                            println("Full Match: ${versparser[0][0]}")
                            Release = versparser[0][1]
                            Version = versparser[0][2]
                            Build = versparser[0][3]
                            } else {
                                error("The version string format does not match the expected pattern.")
                                }
                      } else {
                        def versionPattern = /^(\d+)(?:\.(.*))?_(.+)$/
                        def versparser = (PVERS =~ versionPattern)
                        if (versparser.matches()) {
                          Release = versparser[0][1].toInteger()
                          Version = versparser[0][2] ? versparser[0][2] : "null"
                          Build = versparser[0][3]
                        } else {
                            error("Version string format is invalid: ${PVERS}")
                          }
                      }

                      def TemplateType = ArrayElement[0]
                      def packagever
                      packagearch = PARCH
                      def templatebase
                      def outputfile
                      def changelogversion
                    
                      // Python Script Requires x arguments
                      // template_path (str): Path to the J2 template file.
                      // package_version (str): The JDK version for the package being built.
                      // hardware_architecture (str): The hardware architecture for the package.
                      // package_url (str): The URL of the GitHub binary file for this release.
                      // package_checksum (str): The validated SHA256 checksum of the binary specified in the URL.
                      // package_name (str): The filename of the package binary.
                      // output_file_name (str): The name of the output file to save the rendered content.
                      // current_date (str): The date to be used for changelogs etc.
                      // package_release_version (str): The package release version.
                      // upstream_version (str): The upstream release version.
                      // changelog_version (str): The version to be used in the changelog version
                      // upstreamarm32_version (str): The upstream version to be used for ARM32 on JDK8

                      // Reformat Any Variables For Distribution Specific Oddities

                      if (DistArrayElement == 'alpine') {
                        
                        // If Base Format Reqd = 23_p37 ( Upstream jdk-23+37 )
                        // If Updt Format Reqd = 23.0.1_p11 ( Upstream jdk-23.0.1+11 )
                        // If JKD8 Format Reqd = 8.432.06 ( Upstream jdk8u432b06 )
                        // Upstream Arch For Alpine : **/alpine-linux/x64/temurin/*.tar.gz,**/alpine-linux/x64/temurin/*.zip,**/alpine-linux/x64/temurin/*.sha256.txt,**/alpine-linux/x64/temurin/*.msi,**/alpine-linux/x64/temurin/*.pkg,**/alpine-linux/x64/temurin/*.json,**/alpine-linux/x64/temurin/*.sig
                        // Upstream Arch For Alpine ARM : **/alpine-linux/aarch64/temurin/*.tar.gz,**/alpine-linux/aarch64/temurin/*.zip,**/alpine-linux/aarch64/temurin/*.sha256.txt,**/alpine-linux/aarch64/temurin/*.msi,**/alpine-linux/aarch64/temurin/*.pkg,**/alpine-linux/aarch64/temurin/*.json,**/alpine-linux/aarch64/temurin/*.sig
                        
                        echo "Debug 04"
                        echo "Release = ${Release}"
                        echo "Build = ${Build}"
                        
                        if (Version == "null") {
                            packagever = "${Release}_p${Build}"
                        } else {
                            packagever = "${Release}.${Version}_p${Build}"
                        }

                        // Upstream Version Is Not Required For Alpine
                        upstreamversion = ""

                        if (Release == "8" ) {
                            // Regular expression to split around 'u' and 'b'
                            def versionPattern = /(\d+)(u)(\d+)(b)(\d+)/
                            def versparser = (PVERS =~ versionPattern)
                            if (versparser.matches()) {
                                Release = versparser[0][1]   // Capture before 'u', e.g., "8"
                                Version = versparser[0][3]   // Capture between 'u' and 'b', e.g., "432"
                                Build = versparser[0][5]     // Capture after 'b', e.g., "06"
                                } else {
                                    error("The version string format does not match the expected pattern.")
                                    }
                            packagever = "${Release}.${Version}.${Build}"
                        }
                        // Reformat x64 For Alpine
                        if (PARCH == 'x64') {
                            packagearch = "x86_64"
                        }
                        outputfile = "APKBUILD"

                        echo "Debug 05 Python Parameters For Alpine"
                        echo "Python 1 : Template Path = : ${templatebase}"
                        echo "Python 2 : Package Version = : ${packagever}"
                        echo "Python 3 : Package Arch = : ${packagearch}"
                        echo "Python 4 : Package URL = : ${PKURL}"
                        echo "Python 5 : Package Checksum = : ${PCSUM}"
                        echo "Python 6 : Package Name = : ${PFILE}"
                        echo "Python 7 : Output File Name = : ${outputfile}"
                        echo "Python 8 : Current Date = : ${currentDate}"
                        echo "Python 9 : Package Release Version = : ${PackageReleaseVersion}"
                        echo "Python 10: JDK Upstream Version = : ${upstreamversion}"
                        echo "Python 11 : Changelog Version = :${packagever}"
                        echo "Python 12: ARM32 Version = ${upstreamversion}"

                        // Figure Out Template name
                        templatebase = "./linux_new/${PTYPE}/${DistArrayElement}/src/main/packaging/${PRODUCT}/${Release}/${DistArrayElement}.${PTYPE}${Release}.template.j2"

                        // Check If Template Exists
                        if (!fileExists(templatebase)) {
                          error("Template File Not Found At : ${templatebase}")
                        }

                        def speccmd = "python3 linux_new/generate_spec.py \"${templatebase}\" \"${packagever}\" \"${packagearch}\" \"${PKURL}\" \"${PCSUM}\" \"${PFILE}\" \"${outputfile}\" \"${currentDate}\" \"${PackageReleaseVersion}\" \"${upstreamversion}\" \"${packagever}\" \"${upstreamversion}\""
                        echo "Spec Command : ${speccmd}"
                        def genresult = sh(script: speccmd, returnStatus: true)
                        echo "Result : ${genresult}"
                      } 

                      if (DistArrayElement == 'debian') {

                        echo "Processing Debian Files"
                        // If Base Format Reqd = 23.0.0.0.0+37 ( Upstream jdk-23+37 )
                        // If Updt Format Reqd = 23.0.1.0.0+11 ( Upstream jdk-23.0.1+11 )
                        // If Rebuild Format Reqd = 23.0.1.1.0+5 ( Upstream jdk-23.0.1.1+5 )
                        // If JDK8 8.0.432.0.0+6
                        // Upstream Arch For x64 : **/linux/x64/temurin/*.tar.gz,**/linux/x64/temurin/*.zip,**/linux/x64/temurin/*.sha256.txt,**/linux/x64/temurin/*.msi,**/linux/x64/temurin/*.pkg,**/linux/x64/temurin/*.json,**/linux/x64/temurin/*.sig
                        // Upstream Arch For ARM64 : **/linux/aarch64/temurin/*.tar.gz,**/linux/aarch64/temurin/*.zip,**/linux/aarch64/temurin/*.sha256.txt,**/linux/aarch64/temurin/*.msi,**/linux/aarch64/temurin/*.pkg,**/linux/aarch64/temurin/*.json,**/linux/aarch64/temurin/*.sig
                        // Upstream Arch For s390x : **/linux/s390x/temurin/*.tar.gz,**/linux/s390x/temurin/*.zip,**/linux/s390x/temurin/*.sha256.txt,**/linux/s390x/temurin/*.msi,**/linux/s390x/temurin/*.pkg,**/linux/s390x/temurin/*.json,**/linux/s390x/temurin/*.sig
                        // Upstream Arch For ppc64le : **/linux/ppc64le/temurin/*.tar.gz,**/linux/ppc64le/temurin/*.zip,**/linux/ppc64le/temurin/*.sha256.txt,**/linux/ppc64le/temurin/*.msi,**/linux/ppc64le/temurin/*.pkg,**/linux/ppc64le/temurin/*.json,**/linux/ppc64le/temurin/*.sig
                        // Upstream Arch For RISCV : **/linux/riscv64/temurin/*.tar.gz,**/linux/riscv64/temurin/*.zip,**/linux/riscv64/temurin/*.sha256.txt,**/linux/riscv64/temurin/*.msi,**/linux/riscv64/temurin/*.pkg,**/linux/riscv64/temurin/*.json,**/linux/riscv64/temurin/*.sig
                        // Upstream Arch For ARM32 : **/linux/arm/temurin/*.tar.gz,**/linux/arm/temurin/*.zip,**/linux/arm/temurin/*.sha256.txt,**/linux/arm/temurin/*.msi,**/linux/arm/temurin/*.pkg,**/linux/arm/temurin/*.json,**/linux/arm/temurin/*.sig
                        
                        // Debian Requires 3 Files To Be Generated
                        def debianFiles = ['changelog', 'control', 'rules']

                          if (Release == "8" ) {
                            echo "Debian JDK8"
                            // Extract components from original format
                            def major = PVERS[0]           // Extract major version '8'
                            def versparser = (PVERS =~ /(\d+)u(\d+)b(\d+)/)
                            def minor = versparser[0][2]  // Extract '432'
                            def build = versparser[0][3].replaceAll(/^0+/, '')    // Extract '6'
                            // Construct the new format
                            packagever = "${major}.0.${minor}.0.0+${build}"
                        } else {
                            echo "Debian Not JDK8"
                            if (Version == "null") {
                                packagever = "${Release}.0.0.0.0+${Build}"
                            } else {
                                packagever = "${Release}.${Version}.0+${Build}"
                            }
                            echo "Debian PackageVer = ${packagever}"
                        }

                        echo "Debug 07"
                        echo "PVERS : ${PVERS}"
                        echo "Release = ${Release}"
                        echo "Version = ${Version}"
                        echo "Build = ${Build}"
                        echo "PackageVer = ${packagever}"
                        echo "PackageArch = ${packagearch}"

                        debianFiles.each { debianFilesArrayElement -> 

                        echo "Processing Debian ${debianFilesArrayElement} File"
                        outputfile = debianFilesArrayElement

                        // Figure Out Template name
                        templatebase = "./linux_new/${PTYPE}/${DistArrayElement}/src/main/packaging/${PRODUCT}/${Release}/${DistArrayElement}/${debianFilesArrayElement}.template.j2"

                        // Check If Template Exists
                        if (!fileExists(templatebase)) {
                          error("Template File Not Found At : ${templatebase}")
                        }

                        // echo "Debug 08"
                        // echo "Python 1 : Template Path = : ${templatebase}"
                        // echo "Python 2 : Package Version = : ${packagever}"
                        // echo "Python 3 : Package Arch = : ${packagearchDeb}"
                        // echo "Python 4 : Package URL = : ${PKURL}"
                        // echo "Python 5 : Package Checksum = : ${PCSUM}"
                        // echo "Python 6 : Package Name = : ${PFILE}"
                        // echo "Python 7 : Output File Name = : ${outputfile}"
                        // echo "Python 8 : Current Date = : ${currentDate}"
                        // echo "Python 9 : Package Release Version = : ${PackageReleaseVersion}"
                        // echo "Python 10: Upstream Version = : ${upstreamversion}"
                        // echo "Python 11: Changelog Version = : ${packagever}"
                        // echo "Python 12: ARM32 Version = ${upstreamversion}"

                        def speccmd = "python3 linux_new/generate_spec.py \"${templatebase}\" \"${packagever}\" \"${packagearchDeb}\" \"${PKURL}\" \"${PCSUM}\" \"${PFILE}\" \"${outputfile}\" \"${currentDate}\" \"${PackageReleaseVersion}\" \"${upstreamversion}\" \"${packagever}\" \"${upstreamversion}\""
                        echo "Spec Command : ${speccmd}"
                        def genresult = sh(script: speccmd, returnStatus: true)
                        echo "Result : ${genresult}"
                        
                        }

                      } 
                        
                        if (DistArrayElement == "rhel" || DistArrayElement == "suse") {
                        echo "Debug 09 - Rhel & Suse"
                        echo "PVERS : ${PVERS}"
                        echo "Release = ${Release}"
                        echo "Version = ${Version}"
                        echo "Build = ${Build}"
                        echo "PackageVer = ${packagever}"
                        echo "PackageArch = ${packagearch}"

                        if (Release == "8" ) {
                            echo "RHEL/SUSE JDK8"
                            upstreamversion = params.TAG.replaceFirst("^jdk", "")
                            // Extract components from original format
                            def major = PVERS[0]           // Extract major version '8'
                            def versparser = (PVERS =~ /(\d+)u(\d+)b(\d+)/)
                            def minor = versparser[0][2]  // Extract '432'
                            def build = versparser[0][3].replaceAll(/^0+/, '')    // Extract '6'
                            def formattedBuild = build.toString()padLeft(2, '0')
                            // Construct the new format
                            packagever = "${major}.0.${minor}.0.0.${build}"
                            changelogversion = "${major}.0.${minor}-b${formattedBuild}"
                        } else {
                            echo "RHEL/SUSE Not JDK8"
                            echo "Deubg 09A - ${PVERS}"
                            upstreamversion = params.TAG.replaceFirst("^jdk-", "")

                            if (Version == "null") {
                                packagever = "${Release}.0.0.0.0.${Build}"
                                changelogversion = "${Release}.0.${Version}+${Build}"
                            } else {
                                packagever = "${Release}.${Version}.0.${Build}"
                                changelogversion = "${Release}.0.${Version}+${Build}"
                            }
                        }

                        if (PARCH == 'arm') {
                        // If JDK8 ARM32, Then Need To Deduce Correct Upstream
                        echo "DEBUG00A - Get ARM32 Upstream Version #"
                        echo "PARCH = ${PARCH}"
                        upstreamversionARM32 = upstreamversionARM32.replaceFirst("^jdk", "")
                        upstreamversionARM32 = upstreamversionARM32.replaceAll(/-(jre|jdk)$/, "")
                        echo "Upstream ARM32 : ${upstreamversionARM32}"
                        echo "upstreamVersion : ${upstreamversion}"
                        // DONE
                        }

                        // Figure Out Template name
                        templatebase = "./linux_new/${PTYPE}/${DistArrayElement}/src/main/packaging/${PRODUCT}/${Release}/${PRODUCT}-${Release}-${PTYPE}.template.j2"
                        // Output File Name Only ( defaults to outputting in same location as template )
                        outputfile = "${PRODUCT}-${Release}-${PTYPE}.spec"
                        
                        // Check If Template Exists
                        if (!fileExists(templatebase)) {
                          error("Template File Not Found At : ${templatebase}")
                        }

                        // echo "Debug - 09a - PackageVer = ${packagever}"
                        // echo "Python 1 : Template Path = : ${templatebase}"
                        // echo "Python 2 : Package Version = : ${packagever}"
                        // echo "Python 3 : Package Arch = : ${packagearchRhel}"
                        // echo "Python 4 : Package URL = : ${PKURL}"
                        // echo "Python 5 : Package Checksum = : ${PCSUM}"
                        // echo "Python 6 : Package Name = : ${PFILE}"
                        // echo "Python 7 : Output File Name = : ${outputfile}"
                        // echo "Python 8 : Current Date = : ${currentDateRHEL}"
                        // echo "Python 9 : Package Release Version = : ${PackageReleaseVersion}"
                        // echo "Python 10: Upstream Version = : ${upstreamversion}"
                        // echo "Python 11: Changelog Version = : ${changelogversion}"
                        // echo "Python 12: Upstream ARM32 Version = : ${upstreamversionARM32}"

                        def speccmd = "python3 linux_new/generate_spec.py \"${templatebase}\" \"${packagever}\" \"${packagearchRhel}\" \"${PKURL}\" \"${PCSUM}\" \"${PFILE}\" \"${outputfile}\" \"${currentDateRHEL}\" \"${PackageReleaseVersion}\" \"${upstreamversion}\" \"${changelogversion}\" \"${upstreamversionARM32}\""
                        echo "Spec Command : ${speccmd}"
                        def genresult = sh(script: speccmd, returnStatus: true)
                        echo "Result : ${genresult}"

                        // End Of RHEL SUSE CODE
                      }

                      }

                      }
                    
                    // Tar And Publish The Generated Build Files
                    // May Need Rework
                       sh "tar -czf ./package_build_files.tar.gz ./linux_new/*"
                       sh "pwd"
                       sh "ls -ltr"
                       // Publish the tarball
                       archiveArtifacts artifacts: "package_build_files.tar.gz", allowEmptyArchive: false
                    // Stash The Generated Build Files
                    dir('linux_new') {
                    stash name: 'installercode', includes: '**'
                      
                      
                    }
                  }
              }
          }
// Generate Spec File Stage - End
// Build And Archive Packages Stage - Start
stage('Build & Archive Package') {
    // when {
    //     expression { return params.RELEASE }
    // }
    steps {
        script {
            DISTS_TO_BUILD.each { DistArrayElement ->
                def nodeLabel = ''
                if (DistArrayElement == 'alpine') {
                    nodeLabel = PKGBUILDLABELAPK
                } else if (DistArrayElement == 'debian') {
                    nodeLabel = PKGBUILDLABELDEB
                } else if (DistArrayElement in ['rhel', 'suse']) {
                    nodeLabel = PKGBUILDLABELRHEL
                } else {
                    error "Unknown DistArrayElement: ${DistArrayElement}"
                }

                node(label: nodeLabel) { // Assign node dynamically based on distribution type
                    echo "Build Packages For Arch: ${arch}"
                    echo "Build Packages For PARCH: ${packagearch}"
                    echo "Building For Dist: ${DistArrayElement}"
                    echo "Build Product: ${PRODUCT}"
                    echo "Build Version : ${Release}"

                    // Docker --mount option requires BuildKit
                    env.DOCKER_BUILDKIT = 1
                    env.COMPOSE_DOCKER_CLI_BUILD = 1

                    // Prepare Workspace
                    cleanWs()
                    unstash 'installercode'

                    try {
                        def PackagesToBuild = ['jdk', 'jre']
                        def buildCli
                        PackagesToBuild.each { PackageArrayElement ->
                            echo "Building Package: ${PackageArrayElement} for ${DistArrayElement}"
                            def gBuildTask = (packagearch in ['x86_64', 'amd64']) ?
                                "package${PackageArrayElement}${DistArrayElement} check${PackageArrayElement}${DistArrayElement}" :
                                "package${PackageArrayElement}${DistArrayElement}"
                            
                            // Override Package Arch To Be Dist Specific

                            if (DistArrayElement == "rhel" || DistArrayElement == "suse") {
                              echo "Using build CLI for RHEL/SUSE: ${buildCli}"
                              buildCli = "./gradlew ${gBuildTask} --parallel -PPRODUCT=${PRODUCT} -PPRODUCT_VERSION=${Release} -PARCH=${packagearchRhel}"
                            } else if (DistArrayElement == "debian") {
                               echo "Using build CLI for Debian: ${buildCli}"
                               buildCli = "./gradlew ${gBuildTask} --parallel -PPRODUCT=${PRODUCT} -PPRODUCT_VERSION=${Release} -PARCH=${packagearchDeb}"
                            } else {
                              echo "Using default build CLI: ${buildCli}"
                              buildCli = "./gradlew ${gBuildTask} --parallel -PPRODUCT=${PRODUCT} -PPRODUCT_VERSION=${Release} -PARCH=${packagearch}"
                            }
                                             
                            if (params.ENABLEGPGSIGNING) {
                                def privateKey = 'adoptium-artifactory-rsa-key'
                                withCredentials([file(credentialsId: privateKey, variable: 'GPG_KEY')]) {
                                    buildCli += " -PGPG_KEY_PATH=${GPG_KEY}"
                                }
                            }

                            buildCli = params.ENABLEDEBUG.toBoolean() ? buildCli + ' --stacktrace' : buildCli
                            echo "Build CLI : ${buildCli}"
                            sh("$buildCli")
                        }
                    } catch (Exception ex) {
                        echo "Exception in build for ${DistArrayElement}: ${ex}"
                        currentBuild.result = 'FAILURE'
                    } finally {
                        archiveArtifacts artifacts: '**/build/ospackage/*,**/build/reports/**,**/packageTest/dependencies/deb/*',
                                         onlyIfSuccessful: false, allowEmptyArchive: false
                    }
                }
            }
        }
    }
}
// Build And Archive Packages Stage - End
// Publish Packages Stage - Start
          stage('Publish Packages') {
            agent { label NODE_LABEL }
            tools {
                jfrog 'jfrog-cli'
                }
            when {
                expression { return params.DRY_RUN == false }
            }
              steps {
                  script {
                      echo "This Isnt A Dry Run So Publish Packages"
                      echo "Publishing Packages For : ${distro}"
                      echo "Arch : ${arch}"
                      echo "Publishing For Version : ${Release}"
                      echo ""
                      echo "Retrieving Files"
                      echo ""
                      copyArtifacts projectName: "${env.JOB_NAME}",
                                selector: specific("${env.BUILD_NUMBER}"),
                                filter: '**/build/ospackage/*,**/build/reports/**,**/packageTest/dependencies/deb/*'

                    // Verify files are retrieved
                    // sh 'find .'
                    echo "Done Retrieving Files"

                    // Distro Specific Uploads
                    if (distro == 'alpine-linux') {
                        echo "ALPINE UPLOAD"
                        def UpDistro = "Alpine"
                        def PackFiles = findFiles(glob: '**/build/ospackage/temurin-*j*.apk') // List All Packages To Upload
                        def SrcFiles = findFiles(glob: '**/build/ospackage/temurin-*src*.apk') // List All Sources To Upload
                        def AllFiles = PackFiles + SrcFiles
                        for (PackFile in AllFiles) {
                                 def FileName = PackFile.name
                                 def Target = "https://adoptium.jfrog.io/artifactory/apk/alpine/main/${arch}/${FileName}"
                                 echo "Debug 1000 - Alpine Upload Debugging"
                                 echo "Target = ${Target}"
                                 echo "Distro = ${UpDistro}"
                                 echo "buildArch = ${arch}"
                                 echo "FileName = ${FileName}"
                                 CheckAndUpload(Target, UpDistro, arch, '', '', '', '', '' , FileName)
                        }
                    } else if (distro == 'linux') {
                        echo "Linux Upload"
                        echo "Preparing For Debian Upload"
                        def Distro = "Debian"
                        def PackFilesDeb = findFiles(glob: "**/build/ospackage/temurin-*.deb") // List All Packages To Upload
                        for (PackFile in PackFilesDeb) {
                            def FileName = PackFile.name
                            def Target = "https://adoptium.jfrog.io/artifactory/deb/pool/main/t/temurin-${Release}/${FileName}"
                            echo "Debug 1000 - Debian Upload Debugging"
                            echo "Target = ${Target}"
                            echo "Distro = ${Distro}"
                            echo "buildArch = ${arch}"
                            echo "DistroList = ${distro_list}"
                            echo "FileName = ${FileName}"
                            // deb_distros.each { deb_distro ->
                            // echo "Deb Dist = ${deb_distro}"
                            CheckAndUpload(Target, DebDistro, arch, Release, distro_list, '', '', '', '' )
                            //def CheckAndUpload(String Target, String Distro, String BuildArch, String Version, String DistroList, String Value, String PackageDir, String Key, String FileName) {
                            //}
                            
                        }
                        echo "Preparing For RHEL Upload"
                        def PackFilesRHEL = findFiles(glob: "**/rhel/build/ospackage/t*.rpm") // List All Packages To Upload For Temurin
                        for (PackFile in PackFilesRHEL) {
                            def FileName = PackFile.name
                            // def Target = "https://adoptium.jfrog.io/artifactory/${PACKAGEDIR}/${KEY}/Packages/${FileName}"
                            echo "RHEL FileName = ${FileName}"
                            // echo "Target = ${Target}"
                            //CheckAndUpload(Target, Distro, BUILDARCH, VERSION, DISTROLIST, '', '', '', '' )"
                        }
                        echo "Preparing For SUSE Upload"
                        def PackFilesSUSE = findFiles(glob: "**/suse/build/ospackage/t*.rpm") // List All Packages To Upload For Temurin
                        for (PackFile in PackFilesSUSE) {
                            def FileName = PackFile.name
                            // def Target = "https://adoptium.jfrog.io/artifactory/${PACKAGEDIR}/${KEY}/Packages/${FileName}"
                            echo "SUSE FileName = ${FileName}"
                            // echo "Target = ${Target}"
                            //CheckAndUpload(Target, Distro, BUILDARCH, VERSION, DISTROLIST, '', '', '', '' )"
                        }
                    } else {
                        error "Unknown Distribution"
                    }
                  }
              }
          }
// Publish Packages Stage - End
  }
// Stage Definition - End
}
// Pipeline Definition - End
